language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install flake8 coverage coveralls
  - pip install -e .

before_script:
  - flake8

script:
  - coverage run -p --source=pyamf setup.py test
  - pip install Cython
  - coverage run -p --source=pyamf setup.py test
  - coverage combine

after_success:
  - coveralls
