language: python
python:
  - "2.7"
sudo: false

cache:
  directories:
      - $HOME/.cache/pip

before_install:
  - pip install flake8
  - flake8

install:
  - pip install coverage coveralls
  - pip install -e .

script:
  - coverage run --source=pyamf setup.py test

after_success:
  - coveralls
